### DISCUSSION TITLE
Stream to SSE from another endpoint (upload)

### DISCUSSION THREAD

**Discussion by AlexMikhalev** [poem-web/poem#446] [Q&A] [answered]
Hello all, firstly - poem is great, exactly what I need to move from python fast API. 
The use case I am struggling to implement with poem open API:
Upload file - stream status of background worker after uploading into SSE, in more details:

1. file upload (using open API/upload example, works),
2.  upload kick-offs bash script (tokio child, works), which runs for over 100 seconds,
3.  I would like to stream status updates from the stdout buffer into SSE.  
I tried to follow https://blog.logrocket.com/how-to-build-a-websocket-server-with-rust/ and mix it with open API. They create a channel sender inside the struct, which later wraps around arc mutex. I tried to add  `pub sender: Option<mpsc::UnboundedSender<std::result::Result<String, poem::Error>>>`,  into users_crud for checking, and it fails with `the trait ToJSON is not implemented for UnboundedSender<Result<std::string::String, poem::Error>>` . mpsc is tokio mpsc.

So, what's the right way to trigger the streaming of events from one open API handler to another?

**Comment by sunli829** [comment]
I wrote an example, it's easy:

## try it with

```shell
curl -X 'POST' 'http://localhost:3000/api/exec' -H 'Content-Type: text/plain; charset=utf-8' -d 'ls' -v
```

## Cargo.toml

```toml
[package]
name = "exec"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "1.3.49", features = ["session"] }
poem-openapi = { version = "2.0.21", features = ["swagger-ui"] }
tokio = { version = "1.21.2", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "process",
    "io-util",
] }
tokio-stream = { version = "0.1.11", features = ["sync"] }
```

## main.rs

```rust
use std::process::Stdio;

use poem::{error::BadRequest, listener::TcpListener, Result, Route, Server};
use poem_openapi::{
    payload::{EventStream, PlainText},
    OpenApi, OpenApiService,
};
use tokio::{
    io::{AsyncBufReadExt, BufReader},
    process::Command,
    sync::mpsc,
};
use tokio_stream::wrappers::UnboundedReceiverStream;

struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/exec", method = "post")]
    async fn exec(
        &self,
        command: PlainText<String>,
    ) -> Result<EventStream<UnboundedReceiverStream<String>>> {
        let mut child = Command::new(command.0)
            .stdout(Stdio::piped())
            .spawn()
            .map_err(BadRequest)?;
        let (tx, rx) = mpsc::unbounded_channel();

        tokio::spawn(async move {
            if let Some(stdout) = child.stdout.take() {
                let mut reader = BufReader::new(stdout);
                let mut line = String::new();

                loop {
                    if matches!(reader.read_line(&mut line).await, Ok(0) | Err(_)) {
                        break;
                    }
                    _ = tx.send(line.clone());
                }
            }
        });

        Ok(EventStream::new(UnboundedReceiverStream::new(rx)))
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let app = OpenApiService::new(Api, "demo", "1.0").server("http://localhost:3000/api");
    let ui = app.swagger_ui();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .name("hello-world")
        .run(Route::new().nest("/api", app).nest("/", ui))
        .await
}
```

**Reply by AlexMikhalev** [reply]
That's a great reply. Thank you. Highly appreciate your help and work on Poem.

**Reply by AlexMikhalev** [reply]
I checked it worked and then went through Mozilla documentation: SSE doesn't support post endpoint, and the above example illustrates the issue: post into one endpoint, but stream into SSE shall be read from the get endpoint.

**Reply by sunli829** [reply]
> I checked it worked and then went through Mozilla documentation: SSE doesn't support post endpoint, and the above example illustrates the issue: post into one endpoint, but stream into SSE shall be read from the get endpoint.

you are right!

**Reply by AlexMikhalev** [reply]
My attempt to solve it was to add the sender to users_crud example:
```
/// Create user schema
#[derive(Debug, Object, Clone)]
struct User {
    /// Id
    #[oai(read_only)]
    id: i64,
    /// Name
    #[oai(validator(max_length = 64))]
    name: String,
    /// Password
    #[oai(validator(max_length = 32))]
    password: Password,
    email: Email,
    pub sender: Option<mpsc::UnboundedSender<std::result::Result<String, poem::Error>>>,
    
}
```
it fails with the trait ToJSON is not implemented for UnboundedSender<Result<std::string::String, poem::Error>>. 
Shall we use AddData or is anything better?

**Reply by AlexMikhalev** [reply]
To reiterate - I have two endpoints, one for POST /upload returns JSON ok and another /events/:user_id  returns SSE, the question and problem is how to pass a stream of data between two endpoints.

**Comment by sunli829** [comment, marked as answer]
## Execute bash script with POST

```bash
curl -X 'POST' 'http://localhost:3000/api/exec' -H 'Content-Type: text/plain; charset=utf-8' -d 'ls' -v
```

## Get the outputs with SSE:

```bash
curl 'http://localhost:3000/api/output/afdec250-b5a6-42fe-bd37-d14aeadf9cf4' -H 'Content-Type: text/plain; charset=utf-8' -v 
```

## Cargo.toml

```toml
[package]
name = "ws_example"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "1.3.49", features = ["session"] }
poem-openapi = { version = "2.0.21", features = ["swagger-ui", "uuid"] }
tokio = { version = "1.21.2", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "process",
    "io-util",
] }
tokio-stream = { version = "0.1.11", features = ["sync"] }
uuid = { version = "1.2.2", features = ["v4"] }
```

## main.rs

```rs
use std::{collections::HashMap, process::Stdio};

use poem::{
    error::BadRequest, http::StatusCode, listener::TcpListener, Error, Result, Route, Server,
};
use poem_openapi::{
    param::Path,
    payload::{EventStream, Json, PlainText},
    OpenApi, OpenApiService,
};
use tokio::{
    io::{AsyncBufReadExt, BufReader},
    process::Command,
    sync::{mpsc, Mutex},
};
use tokio_stream::wrappers::UnboundedReceiverStream;
use uuid::Uuid;

type OutputStream = EventStream<UnboundedReceiverStream<String>>;

#[derive(Default)]
struct Api {
    outputs: Mutex<HashMap<Uuid, OutputStream>>,
}

#[OpenApi]
impl Api {
    #[oai(path = "/exec", method = "post")]
    async fn exec(&self, command: PlainText<String>) -> Result<Json<Uuid>> {
        let mut child = Command::new(command.0)
            .stdout(Stdio::piped())
            .spawn()
            .map_err(BadRequest)?;
        let (tx, rx) = mpsc::unbounded_channel();

        tokio::spawn(async move {
            if let Some(stdout) = child.stdout.take() {
                let mut reader = BufReader::new(stdout);
                let mut line = String::new();

                loop {
                    if matches!(reader.read_line(&mut line).await, Ok(0) | Err(_)) {
                        break;
                    }
                    _ = tx.send(line.clone());
                }
            }
        });

        let id = Uuid::new_v4();
        self.outputs
            .lock()
            .await
            .insert(id, EventStream::new(UnboundedReceiverStream::new(rx)));
        Ok(Json(id))
    }

    #[oai(path = "/output/:id", method = "get")]
    async fn output(&self, id: Path<Uuid>) -> Result<OutputStream> {
        self.outputs
            .lock()
            .await
            .remove(&id)
            .ok_or_else(|| Error::from_status(StatusCode::NOT_FOUND))
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let app =
        OpenApiService::new(Api::default(), "demo", "1.0").server("http://localhost:3000/api");
    let ui = app.swagger_ui();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .name("hello-world")
        .run(Route::new().nest("/api", app).nest("/", ui))
        .await
}
```
