### ISSUE TITLE
poem_openapi - no method named `swagger_ui` found for struct `OpenApiService` in the current scope

### ISSUE THREAD

**Issue by sccheruku** [poem-web/poem#271]
I'm trying to follow along with the documentation [here](https://github.com/poem-web/poem/blob/master/poem-openapi/README.md#example) 

But the line: 
```rust
let ui = api_service.swagger_ui();
```
returns the error: https://github.com/poem-web/poem/blob/master/poem-openapi/README.md#example

Any suggestions on what I can to do fix this? 

Here is my cargo.toml

```toml
[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "1.3.29"
poem-openapi = "1.3.29"
tokio = { version = "1", features = ["full"] }

```

**Comment by sunli829** [comment]
Add the `swagger-ui` feature.

```toml
[dependencies]
poem = "1.3.29"
poem-openapi = { version = "1.3.29", features = ["swagger-ui"] }
```
