### ISSUE TITLE
OpenApi: Path generation regression between `3.0.3` and `3.0.4`

### ISSUE THREAD

**Issue by hankjordan** [poem-web/poem#648]
## Expected Behavior
Endpoint should be `/path/to/endpoint`

## Actual Behavior
Endpoint is `/path/to/endpoint/`

## Steps to Reproduce the Problem
- Update from `3.0.3` to `3.0.4`

Newer version fails to strip the slash leading to **broken links between patch versions**

**Without changing any handler / openapi code.**

<details>
  <summary>Minimum Reproducible Example</summary>

```rust
use poem::{listener::TcpListener, Route};
use poem_openapi::{OpenApi, OpenApiService};

struct Api;

#[OpenApi(prefix_path = "/path/to/endpoint")]
impl Api {
    #[oai(path = "/", method = "get")]
    async fn index(&self) {
        unimplemented!()
    }
}

#[tokio::main]
async fn main() {
    let api = OpenApiService::new(Api, "API", "test").server("/");
    let app = Route::new().nest("/docs", api.rapidoc()).nest("/", api);
    poem::Server::new(TcpListener::bind("0.0.0.0:8000"))
        .run(app)
        .await
        .unwrap();
}
  ```
  `3.0.3` gives `/path/to/endpoint`
```toml
[package]
name = "poem-path-regression-mre"
edition = "2021"
version = "0.1.0"

[dependencies]
tokio = { version = "1.29", features = ["full"] }
poem = "1.3"
poem-openapi-derive = "=3.0.3"
poem-openapi = { version = "=3.0.3", features = ["rapidoc"] }
```
`3.0.4` gives `/path/to/endpoint/`
```toml
[package]
name = "poem-path-regression-mre"
edition = "2021"
version = "0.1.0"

[dependencies]
tokio = { version = "1.29", features = ["full"] }
poem = "1.3"
poem-openapi-derive = "=3.0.4"
poem-openapi = { version = "=3.0.4", features = ["rapidoc"] }
```
</details>

## Other Information
Related: #645
