### ISSUE TITLE
Openapi: wrong format for integers

### ISSUE THREAD

**Issue by DDtKey** [poem-web/poem#760]
## Expected Behavior

```rs
#[derive(Debug, Object, Clone)]
#[oai(rename_all = "snake_case", read_only_all = true)]
struct MyStructure {
    a: u64,
    b: u16,
}
```

Should produce openapi-schema with `minimum` & `maximum` instead of `uint64` and `uint16`.

```yaml
MyStructure: 
      type: object
      properties:
        a:
          type: integer
          minimum: 0
        b:
          type: integer
          minimum: 0
          maximum:  65535
```

There is no such formats in openapi specification.  It's controlled by `minimum` / `maximum` & `exclusiveMinimum`
Exists only one unsigned definition: [uint8](https://spec.openapis.org/registry/format/uint8)

## Actual Behavior
Currently it produces 

```json
MyStructure: 
      type: object
      properties:
        a:
          type: integer
          format: uint64
        b:
          type: integer
          format: uint16
```
