### ISSUE TITLE
Specify enum paths in OpenAPI

### ISSUE THREAD

**Issue by musjj** [poem-web/poem#887]
## Description of the feature

Currently, there's no nice way to specify enums in paths. You can do something like this:

```rust
pub struct Api;

#[derive(Enum, Deserialize)]
#[oai(rename_all = "lowercase")]
pub enum Choices {
    Foo,
    Bar,
}

#[OpenApi]
impl Api {
    #[oai(path = "/pick/:choices", method = "get")]
    pub async fn pick(&self, choices: Path<Choices>) -> PlainText<String> {
        PlainText("hello world".to_string())
    }
}
```

But the resulting paths will be `/pick/Foo` and `/pick/Bar`. The enum choices will not be included in the spec either.

In OpenAPI, it should be possible to define enums in the path:

```yaml
paths:
  /pick/{choices}:
    get:
      parameters:
      - in: path
        name: choices
        required: true
        type: string
        enum: [foo, bar]
```

It would be nice if we can express this constraint with `poem-openapi`.
