### ISSUE TITLE
Additional `style` field in generated OpenAPI Yaml that fails validation

### ISSUE THREAD

**Issue by ben-iron** [poem-web/poem#992]
After updating to the current version, the generated OpenAPI yaml includes a `style: null` field like so:

```
      - name: id
        schema:
          type: string
          format: uuid
        in: path
        description: the description
        required: true
        deprecated: false
        explode: true
        style: null
```

(see `style: null` in the last line)
This is not OpenAPI conform, where it has to be one of form, simple, spaceDelimited, etc. I can't figure out how to disable this.
