### ISSUE TITLE
Poem broken again ! "csrf" has been downgraded  v0.4.2 -> v0.4.1 | new : v0.5.0

### ISSUE THREAD

**Issue by rxdiscovery** [poem-web/poem#993]
Hello,

The maintainer of the “csrf” crate has corrected the Semver, and transferred the changes to 0.5, which makes poem version 3.1.7 incompatible.

You need to change the version in the Cargo.tom file to 0.5.

____

```toml
poem = {version = "3.1.7"}
poem-openapi = { version = "5.1.8" }
```

Thanks
